# ========================================
# GESTURE CONTROL SYSTEM - CONFIGURATION
# ========================================

# === ACTIVE CONTROLLER ===
# Options: "system", "spotify", "youtube"
ACTIVE_CONTROLLER = "system"

# === GESTURE SENSITIVITY SETTINGS ===
# Swipe Detection (arm-based movement)
SWIPE_THRESHOLD_CM = 12
SWIPE_MIN_VELOCITY = 0.1

# Pinch Detection (for volume control - "yapping hand" gesture)
PINCH_DEADZONE_CM = 2.0        # Sensitivity for thumb-pinky movement
PINCH_MIN_DISTANCE = 3
PINCH_MAX_DISTANCE = 20
PINCH_VOLUME_SENSITIVITY = 5   # Balanced for Windows 11 response

# Fist Detection
FIST_CONFIDENCE_THRESHOLD = 0.8

# === TIMING & COOLDOWN ===
GESTURE_COOLDOWN = 0.8
GESTURE_HOLD_TIME = 0.25
STATE_TRANSITION_DELAY = 0.15

# === ANTI-JITTER & DEPTH ===
LANDMARK_BUFFER_SIZE = 7
POSITION_SMOOTHING_FACTOR = 0.3
JITTER_THRESHOLD_PX = 2
MIN_MOVEMENT_THRESHOLD = 0.005

# Depth Compensation
MIN_DEPTH_CM = 10.0
MAX_DEPTH_CM = 60.0
DEPTH_SCALE_FACTOR = 1.5

# === CAMERA SETTINGS ===
CAMERA_INDEX = 0
CAMERA_WIDTH = 540
CAMERA_HEIGHT = 380
CAMERA_FPS = 60

# === MEDIAPIPE SETTINGS ===
MP_MIN_DETECTION_CONFIDENCE = 0.7
MP_MIN_TRACKING_CONFIDENCE = 0.7
MP_MODEL_COMPLEXITY = 1
MP_MAX_HANDS = 1

# === VISUAL FEEDBACK ===
SHOW_SKELETON = True
SHOW_METRICS = True
SHOW_GESTURE_NAME = True
SHOW_ACTION_FEEDBACK = True
SHOW_COOLDOWN_TIMER = True
SHOW_VOLUME_BAR = True

# UI Colors (BGR format)
COLOR_SKELETON = (0, 255, 0)    # Green
COLOR_JOINTS = (0, 0, 255)      # Red
COLOR_FINGERTIPS = (255, 0, 0)  # Blue
COLOR_TEXT = (255, 255, 255)    # White
COLOR_ACTION = (0, 255, 255)    # Yellow
COLOR_COOLDOWN = (0, 165, 255)  # Orange

# === DEBUG MODE ===
DEBUG_MODE = True
LOG_GESTURES = True
SAVE_METRICS = False
